export const SIGNUP = 'SIGNUP'
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS'
export const SIGNUP_FAILURE = 'SIGNUP_FAILURE'

export const SIGNIN = 'SIGNIN'
export const SIGNIN_SUCCESS = 'SIGNIN_SUCCESS'
export const SIGNIN_FAILURE = 'SIGNIN_FAILURE'

export const LOGOUT = 'LOGOUT'
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS'
export const LOGOUT_FAILURE = 'LOGOUT_FAILURE'

export const CREATE_PREDICTORS_FIRSTDISPLAY = 'CREATE_PREDICTORS_FIRSTDISPLAY'
export const CREATE_PREDICTORS_SECONDDISPLAY = 'CREATE_PREDICTORS_SECONDDISPLAY'
export const CREATE_PREDICTORS_THIRDDISPLAY = 'CREATE_PREDICTORS_THIRDDISPLAY'

export const MODALTYPE_FIRSTDISPLAY = 'MODALTYPE_FIRSTDISPLAY'
export const MODALTYPE_SECONDDISPLAY = 'MODALTYPE_SECONDDISPLAY'
export const MODALTYPE_THIRDDISPLAY = 'MODALTYPE_THIRDDISPLAY'

export const MODALTYPE2_FIRSTDISPLAY = 'MODALTYPE2_FIRSTDISPLAY'
export const MODALTYPE2_SECONDDISPLAY = 'MODALTYPE2_SECONDDISPLAY'
export const MODALTYPE2_THIRDDISPLAY = 'MODALTYPE2_THIRDDISPLAY'

export const PREDICTORS_EDIT_MODEL_DATA = 'PREDICTORS_EDIT_MODEL_DATA'
export const DATASET_COMPONENT = 'DATASET_COMPONENT'
export const DATASET_COMP_FEATURES = 'DATASET_COMP_FEATURES'
export const PREDICTORS_COMP_FEATURES = 'PREDICTORS_COMP_FEATURES'
export const OPTIMIZER_EDIT_MODAL = 'OPTIMIZER_EDIT_MODAL'

export const CREATE_AN_OPTIMIZER = 'CREATE_AN_OPTIMIZER'
export const CREATE_PREICTORS_FLAG = 'CREATE_PREICTORS_FLAG'
export const STEPPER_STEP = 'STEPPER_STEP'
export const CREATE_PREDICTORS_COMPONENT_CHANGE = 'CREATE_PREDICTORS_COMPONENT_CHANGE'

export const CREATE_A_DASHBOARD = 'CREATE_A_DASHBOARD'
export const EDIT_DASHBOARD_MODAL = 'EDIT_DASHBOARD_MODAL'
export const OPTIMIZER_COMP_FEATURES = 'OPTIMIZER_COMP_FEATURES'

export const PREDICTORS_EDIT_MODAL_FLAG = 'PREDICTORS_EDIT_MODAL_FLAG'
export const DATASET_POPOVER = 'DATASET_POPOVER'
export const PREDICTORS_POPOVER = 'PREDICTORS_POPOVER'